# Generated by Django 3.0.8 on 2020-10-01 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('show_only_nickname', models.BooleanField()),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Swearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swearing', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=3)),
                ('confirmed', models.BooleanField()),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keiksmai_frontend.Site_user')),
            ],
        ),
    ]
